### ISSUE TITLE
Usage with Roblox LSP

### ISSUE THREAD

**Issue by richie0866** [arnoson/monaco-lua-example#2]
How would you use this example with [Roblox LSP](https://github.com/NightrainsRbx/RobloxLsp)? I tried specifying Roblox LSP's binary & main.lua file and adding the -E flag [here](https://github.com/arnoson/monaco-lua-example/blob/main/server/src/launch.ts#L16), and though I see no errors, it doesn't seem to be doing anything to the editor.

**Comment by richie0866** [comment]
Resolved, needed to modify Roblox LSP

**Comment by Tamim468** [comment]
I have same question too, not only that but also the localhost says Upgrade Required, you can go to my issue for more information
